# Generated by Django 2.0.3 on 2018-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('creationTime', models.CharField(default='blahcreation', max_length=20)),
                ('lastSignInTime', models.CharField(default='blahlastsignin', max_length=20)),
                ('phoneNumber', models.CharField(default='blahphone', max_length=20)),
                ('photoURL', models.CharField(default='blahphoto', max_length=200)),
                ('uid', models.CharField(default='blahuid', max_length=200)),
            ],
        ),
    ]
