# Generated by Django 2.1.2 on 2018-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0003_auto_20181109_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
