# Generated by Django 2.0.3 on 2018-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0003_auto_20181109_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='blahuid', max_length=200, unique=True),
        ),
    ]
