# Generated by Django 2.1.2 on 2018-11-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0004_auto_20181111_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserAPI.User')),
            ],
        ),
    ]
